# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'ExampleCoinList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ExampleCoinList
  pod 'CoinList', :path => '../'
  pod 'LucasCoinAPI'
#  pod 'API', :git => 'https://github.com/lucaswkuipers/API.git'

  target 'ExampleCoinListTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExampleCoinListUITests' do
    # Pods for testing
  end

end
